### PR TITLE
Add Native AOT for Android experiment

### PR DESCRIPTION
**Pull request by kotlarmilos**
## Description

This PR adds Native AOT for Android experiment under the completed projects section.

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Comment by MichalStrehovsky** [comment]
Wasn't this branch _just_ created? Should this go to the "Active Experimental Projects" section above? Or are we already done with this?

**Comment by fanyang-mono** [comment]
> Wasn't this branch _just_ created? Should this go to the "Active Experimental Projects" section above? Or are we already done with this?

We are done with the experiment for now. We've decided not to proceed atm.

**Comment by kotlarmilos** [comment]
Thanks for merging this. We will provide more details and findings on the experiment.

**Comment by MichalStrehovsky** [comment]
@jkotas are you an admin on this repo? Looks like the source branch for this PR `feature/add-nativeaot-android-experiment` triggered branch protection rules (because of the "feature" prefix I assume) and it's impossible to delete.

**Comment by jkotas** [comment]
deleted the feature/add-nativeaot-android-experiment branch

**Pull request merged**
