### PR TITLE
Add access violation location in ASM

### PR DESCRIPTION
**Pull request by kant2002**
That location used in `InInterfaceDispatchHelper` to check for possible NRE
See #1424

### CODE REVIEW

**Comment by jkotas** [comment]
I would be also nice to update `UnwindSimpleHelperToCaller` to match. It should be:

```
...
    uintptr_t adjustedFaultingIP = pContext->GetLr();
#if defined(HOST_ARM)
    if (InInterfaceDispatchHelper(faultingIP))
        pContext->SetSp(pContext->GetSp()+2*sizeof(uintptr_t));
#endif
...
```

**Comment by kant2002** [comment]
That's for manually pop data from stack which was previously added. Correct?

**Comment by jkotas** [comment]
BTW: An alternative way to deal with this would be to use redzone to save the registers (8 bytes below the current sp). I see that the code later in the function is using redzone already. It would save you from dealing with pushing and popping the registers.

**Comment by jkotas** [comment]
> That's for manually pop data from stack which was previously added. Correct?

Right

**Comment by kant2002** [comment]
> BTW: An alternative way to deal with this would be to use redzone to save the registers

I hope I understand the idea correctly.

**Review by jkotas — APPROVED** [review]
Yes, I think you got it right. Thanks!

**Pull request merged**
