### PR TITLE
Fix CI for regexsrm branch

### PR DESCRIPTION
**Pull request by danmoseley**

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by danmosemsft** [comment]
Failures are
```
2021-02-06T02:17:42.8985553Z ##[error].dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(397,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Error compiling /__w/1/s/artifacts/bin/pkg/net6.0/runtime/Linux-Release-x64/System.Text.RegularExpressions.dll: Target-dependent SIMD vector types may not be used with ngen.
```
@veanes I believe this is because you introduced use of `Vector<T>` without guarding it with a test of `Vector.IsHardwareAccelerated`. This causes the error above when precompiling, as the precompiler cannot assume whether anything beyond SSE2 is available; it will treat `Vector.IsHardwareAccelerated` as a constant false.

You'll want to either add this guard (presuambly with a software fallback path) or, if possible, remove the implementation in favor of the built in string.IndexOf, which in recent .NET is vectorized. If you push the change to this branch, then it will validate it.

**Comment by jkotas** [comment]
>  I believe this is because you introduced use of Vector<T> without guarding it with a test of Vector.IsHardwareAccelerated.

`Vector<T>` should not require guarding with `Vector.IsHardwareAccelerated` for functional correctness. This error sounds like crossgen bug. 

Having said this, it is a good idea to guard uses of `Vector<T>` with Vector.IsHardwareAccelerated for good performance.

**Comment by danmosemsft** [comment]
Alright, opened a bug. The necessary work here seems the same.

**Comment by pgovind** [comment]
@safern: Do you know why the console isn't showing more output when a test fails? I see only 
```
Console log: 'System.Text.RegularExpressions.Tests' from job 213c7352-57b0-4998-b292-564d4f05cefb (windows.10.amd64.serverrs5.open.rt) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504 on a0020Y9
running %HELIX_CORRELATION_PAYLOAD%\scripts\c89aa5103b7643a89d87e254ee8d4331\execute.cmd in C:\h\w\984A08EC\w\B91E0A3E\e max 900 seconds
```

Don't we see some sort of a call stack usually?

**Comment by danmoseley** [comment]
Some have stacks eg
```

System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.


Stack trace
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:line 479
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:line 931
   at System.Text.RegularExpressions.SRM.BDDAlgebra.MkAnd(BDD a, BDD b) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/BDDAlgebra.cs:line 115
   at System.Text.RegularExpressions.SRM.DecisionTree.<>c__DisplayClass6_0.<Precompute>b__0(Int32 i) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/matcher/DecisionTree.cs:line 68
   at System.Text.RegularExpressions.SRM.DecisionTree.Precompute(CharSetSolver solver, BDD[] partition, Int32 precomputeLimit) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/matcher/DecisionTree.cs:line 77
   at System.Text.RegularExpressions.SRM.DecisionTree.Create(CharSetSolver solver, BDD[] partition, UInt16 precomputeLimit) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/matcher/DecisionTree.cs:line 52
   at System.Text.RegularExpressions.SRM.BV64Algebra.Create(CharSetSolver solver, BDD[] minterms) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/BV64Algebra.cs:line 41
   at System.Text.RegularExpressions.SRM.SymbolicRegexUInt64..ctor(SymbolicRegexNode`1 sr, CharSetSolver solver, SymbolicRegexBuilder`1 srBuilder, BDD[] minterms, RegexOptions options) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/matcher/SymbolicRegexMatcher.cs:line 71
   at System.Text.RegularExpressions.SRM.Regex..ctor(RegexNode rootNode, RegexOptions options) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/Regex.cs:line 39
   at System.Text.RegularExpressions.Regex.InitializeSRM(RegexNode rootNode, RegexOptions options) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 146
   at System.Text.RegularExpressions.Regex.Init(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 126
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 77
   at System.Text.RegularExpressions.RegexCache.GetOrAdd(String pattern, RegexOptions options, TimeSpan matchTimeout) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.Cache.cs:line 135
   at System.Text.RegularExpressions.Regex.Match(String input, String pattern, RegexOptions options) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.Match.cs:line 66
   at System.Text.RegularExpressions.Tests.AttRegexTests_SRM.Test(String pattern, String input, String captures) in /_/src/libraries/System.Text.RegularExpressions/tests/RegexSRMTests.cs:line 1645
```

**Comment by danmoseley** [comment]
```

Assert.StartsWith() Failure:\r\nExpected: System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.\r\n   at System.Collections.Generic.Dictionary2.FindValue(TKey key) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:line 365\r\n at System.Collections.Generic.Dictionary2.TryGetValue(TKey key, TValue& value) in //src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:line 939\r\n   at System.Text.RegularExpressions.SRM.BDDAlgebra.MkAnd(BDD a, BDD b) in //src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/BDDAlgebra.cs:line 115\r\n   at System.Text.RegularExpressions.SRM.PartitonTree1.Refine(PRED psi) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/MintermGenerator.cs:line 179\r\n at System.Text.RegularExpressions.SRM.PartitonTree1.Refine(PRED psi) in //src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/MintermGenerator.cs:line 208\r\n   at System.Text.RegularExpressions.SRM.MintermGenerator1.GenerateMinterms(Boolean useEquivalenceChecking, PRED[] preds)+MoveNext() in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/algebras/MintermGenerator.cs:line 94\r\n at System.Text.RegularExpressions.SRM.SymbolicRegexNode1.EnumerateMinterms(S[] preds)+MoveNext() in //src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/SymbolicRegexNode.cs:line 1462\r\n   at System.Collections.Generic.List1..ctor(IEnumerable1 collection) in //src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs:line 91\r\n   at System.Text.RegularExpressions.SRM.SymbolicRegexNode`1.ComputeMinterms() in //src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/SymbolicRegexNode.cs:line 1453\r\n   at System.Text.RegularExpressions.SRM.Regex..ctor(RegexNode rootNode, RegexOptions options) in //src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/srm/Regex.cs:line 30\r\n   at System.Text.RegularExpressions.Regex.InitializeSRM(RegexNode rootNode, RegexOptions options) in //src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 146\r\n   at System.Text.RegularExpressions.Regex.Init(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture) in //src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 95\r\n   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture) in //src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 85\r\n   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options) in //src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 60\r\n   at System.Text.RegularExpressions.Tests.RegexSRMTests.ValidateSRMRegex_Monotests(String pattern, RegexOptions options, String input, String expected) in //src/libraries/System.Text.RegularExpressions/tests/RegexSRMTests.cs:line 142\r\nActual:   Fail.
```

**Comment by veanes** [comment]
I created a separate pull request for taking care of the failing unit tests due to thread safety.

**Comment by veanes** [comment]
merged at this point, the failing unit tests related to SRM non-thread-safety should be fixed by pull request #680

**Pull request merged**
