### PR TITLE
NativeAOT-LLVM: Merge commit '4f78607507f1d189633cc320f3841c845f4f4b7f' 

### PR DESCRIPTION
**Pull request by yowl**
This PR moves the NativeAOT-LLVM branch forward just a little. (before the targetosarch.h addition)

cc @SingleAccretion

 Conflicts:
	docs/workflow/building/coreclr/nativeaot.md
	eng/pipelines/runtimelab.yml
	src/coreclr/jit/CMakeLists.txt
	src/coreclr/jit/lclvars.cpp
	src/coreclr/nativeaot/CMakeLists.txt
	src/tests/run.cmd

### CODE REVIEW

**Review by SingleAccretion — APPROVED** [review]
I wonder what is the best way to have GH make conflict resolution reviewable. One distinct commit which bulk resolves them at the end of a chain which accumulates `<<<<`s, perhaps?

**Comment by yowl** [comment]
IndirectionNode is gone and with it `RhpReversePInvoke2`....

**Comment by yowl** [comment]
Going to have to look at https://github.com/dotnet/runtimelab/pull/1532 which I'd forgotten about

**Comment by yowl** [comment]
> One distinct commit which bulk resolves them at the end of a chain which accumulates `<<<<`s, perhaps?

I will try that for the next one.

**Pull request merged**
