### PR TITLE
[NativeAOT LLVM] Fix typo in llvm version in docs

### PR DESCRIPTION
**Pull request by maraf**

### CODE REVIEW

**Review by SingleAccretion — APPROVED** [review]
I am thinking of automatic this LLVM building using the CI script soon.

**Review by yowl — APPROVED** [review]
Thanks!

**Comment by maraf** [comment]
> I am thinking of automatic this LLVM building using the CI script soon.

Have you considered using LLVM nuget packages we have for mono based workloads?

**Comment by SingleAccretion** [comment]
> Have you considered using LLVM nuget packages we have for mono based workloads?

It's the long term (i. e. if/when the project goes upstream) goal. The current solution is simpler infrastructure-wise. Also, it allows us to update LLVM independently and build it in debug, i. e. it is better for local development.

**Pull request merged**
