### PR TITLE
Sync JsonCodeGen experiment with latest dotnet/runtime master

### PR DESCRIPTION
**Pull request by joperezr**
cc: @ericstj @layomia 

This is the second part of the splitted ingestion.

### CODE REVIEW

**Comment by joperezr** [comment]
@safern @ericstj looks like our assumption of the problem being the size of the PR was wrong, this is similar size to the previous one and AzDO isn't working again, so it must be that there is one commit that is triggering the issue.

**Comment by safern** [comment]
It seems like there is a way to skip CI based on commit message as @ericstj suggested (good catch). 

https://github.com/Microsoft/azure-pipelines-agent/issues/1270#issuecomment-475768025

Maybe there is a commit containing any of those combinations?

**Comment by joperezr** [comment]
I have checked all messages and body and none of those have any of those combinations

**Comment by ericstj** [comment]
Maybe something more mundane like a change to yml that we need to react to?

**Comment by joperezr** [comment]
I have checked the yml though and it looks correct, and it is being processed and evaluated correctly, somehow we are missing something here

**Comment by ericstj** [comment]
Did you review changes here: https://github.com/joperezr/runtimelab/commits/runtime-ingestion/eng/pipelines

**Comment by joperezr** [comment]
Didn't find a good way of reviewing all changes that were going in with this but I  went to AzDo, selected this branch and downloaded the full expanded pipeline, which basically evaluates all parameters and conditions, and the one I got matches what we had before

**Comment by ericstj** [comment]
Maybe we need to get someone from AzDo to tell us what's going on?

**Comment by ericstj** [comment]
I suspect we'll need the code sync'ed soonish as feature work will be starting soon.  cc @layomia @kevinwkt

**Comment by safern** [comment]
We're looking at this with AzDo and it seems it is the size of the PR (number of files changed). We tried running the pipeline manually from the PR branch and we got:

>Encountered error(s) while parsing pipeline YAML: Could not get the latest source version for repository dotnet/runtimelab hosted on https://github.com/ using ref refs/pull/14/merge. GitHub reported the error, "The request could not be processed because too many files changed"

So while they investigate maybe we want to trim the size of the PR down by splitting into multiple PRs again.

**Comment by ericstj** [comment]
I see, well if its size of the PR, we could just merge it without validation to get past this.  I mean hypothetically we're merging a known good codebase.  That's effectively how we're not hitting this during codeflow of branches for release of dotnet/runtime.

**Comment by safern** [comment]
We were able to run a build against this branch... https://dev.azure.com/dnceng/public/_build/results?buildId=734323&view=results

Just FYI @joperezr was able to get the number of files changed:
```
git diff mainrepo/JsonCodeGen --shortstat
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 23674 and retry the command.
 58843 files changed, 9488228 insertions(+), 9358346 deletions(-)
```

😄

**Comment by ericstj** [comment]
It looks like that build hit the Unix consolelogger test failures due to SuppressGCTransitionAttribute.  We will need latest commits.

**Comment by joperezr** [comment]
Ok I have now updated the branch with latest dotnet/runtime and will now queue manually a new CI build before merging:

https://dev.azure.com/dnceng/public/_build/results?buildId=743467&view=results

Will merge this once everything is green.

FYI: with this PR I manually added a change that deletes the CODEOWNERS file from the fork, and I did this so that future ingestions of dotnet/runtime won't trigger automatic reviewers.

**Pull request merged**
