### PR TITLE
Fixing Internal pool names in yaml to unblock official build

### PR DESCRIPTION
**Pull request by joperezr**
FYI: @MosheWolberg @ericstj

### CODE REVIEW

**Comment by joperezr** [comment]
I've tested this with a dummy internal build and things seem to be working.

**Comment by jkotas** [comment]
Could you please submit the same change to https://github.com/dotnet/runtimelab/tree/standalone-template as well?

**Review by jkotas — APPROVED** [review]

**Comment by joperezr** [comment]
Yup, I was planning to do that next 😄

**Review by ericstj — APPROVED** [review]
Looks to me like this is working now.  Thanks for fixing it!

**Comment by joperezr** [comment]
Yup, I'll wait for the internal build to finish. Once it's done I'll merge this and put up a PR for the template branch

**Pull request merged**
