### PR TITLE
First stab at Microsoft.DotNet.ILCompiler package

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
This is based off the crossgen2 package.

We still don't have the BuildIntegration files, but I'm keen to see how spectacularly this is going to fail in the CI.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
@jkotas This now produces _something_.

The current problems with this:
* The runtime.json in the aggregate package refers to packages such as "runtime.win-x64.Microsoft.DotNet.ILCompiler"
 (expected), but the build actually generates "Microsoft.DotNet.ILCompiler.win-x64.5.0.0-dev.nupkg" (unexpected).
* As a result of that, I can't really test this locally because I can't convince NuGet to consume the runtime specific package.

The package "looks" okay. One of the problems with the non-runtime-specific package is that it has runtime-specific cruft in it, but that is probably only hurting size.

I don't know if this is something the rest of the infra papers over before publishing. I assume RID specific package build publishing works otherwise.

**Comment by jkoritzinsky** [comment]
@MichalStrehovsky the results you're seeing are because the infrastructure is producing a framework pack (the .NET Core 3.0+ method of consuming the runtime) instead of a runtime-specific package (the .NET Core 2.x and previous way).

Try setting `BuildRuntimePackages` to `true` in the pkgproj instead of setting `BuildRidSpecificPacks` to `true`.

That should enable building the RID-specific NuGet packages the way the lineup package expects.

**Comment by MichalStrehovsky** [comment]
> Try setting BuildRuntimePackages to true in the pkgproj instead of setting BuildRidSpecificPacks to true.

Works like charm. Thank you @jkoritzinsky!

**Comment by MichalStrehovsky** [comment]
Along with #71 and #72, this produces a workable NuGet package.

I say workable, because it requires passing `/subsystem:console /entry:wmainCRTStartup` as additional arguments to linker because otherwise we get `fatal error LNK1561: entry point must be defined`. I haven't yet figured out the magic voodoo that we miss in the Bootstrapper.lib produced in this repo compared to Bootstrapper.lib from the CoreRT repo to make this issue go away.

**Pull request merged**
