### PR TITLE
Update location of Emscripten

### PR DESCRIPTION
**Pull request by kant2002**
Docs mention `dotnet/emsdk` but CI use `emscripten-core/emsdk`. Also very specific commit needed. Document that with snippet of code.

### CODE REVIEW

**Comment by yowl** [comment]
I wonder if its best to leave these docs alone as they relate to the official coreclr build.  We can add your instructions about the specific version of emsdk to  docs/using-nativeaot/compiling.md ?

**Comment by kant2002** [comment]
This part is specifically for NativeAOT-LLVM, I did not see any issue changes them since nothing remotely like that in NativeAOT and CoreCLR.

**Comment by kant2002** [comment]
And `docs/using-nativeaot/compiling.md` specifically for developer who want compile application using NativeAOT-LLVM, not develop using it.

**Comment by yowl** [comment]
Ok, fine with me.

**Review by jkotas — APPROVED** [review]
Thank you

**Pull request merged**
