### PR TITLE
[NativeAOT-LLVM] support System.Net.Http.HttpClient - leftovers

### PR DESCRIPTION
**Pull request by pavelsavara**
This is https://github.com/dotnet/runtimelab/pull/2614 rebased to [latest](https://github.com/dotnet/runtimelab/commit/e1513fb58a7691d7e5b509cfa7f5f8c65481875a) NAOT-LLVM

cc @dicej

I don't think this should be merged as is, but rather cherry-picked and closed

### CODE REVIEW

**Comment by pavelsavara** [comment]
The trailing headers for upstream are in https://github.com/dotnet/runtime/pull/107795 but they are blocked by the TE headers support https://github.com/WebAssembly/WASI/issues/798

**Comment by pavelsavara** [comment]
Related issue https://github.com/dotnet/runtimelab/issues/2648

**Comment by dicej** [comment]
I've rebased this onto the latest NativeAOT-LLVM `HEAD` and am in the process of breaking it into separate PRs.

**Comment by dicej** [comment]
I've split this up into:
https://github.com/dotnet/runtimelab/pull/2775
https://github.com/dotnet/runtimelab/pull/2776
https://github.com/dotnet/runtime/pull/109838
https://github.com/dotnet/runtime/pull/109839
https://github.com/dotnet/runtime/pull/109840
https://github.com/dotnet/runtimelab/pull/2777
https://github.com/dotnet/runtimelab/pull/2778

**Pull request closed without merging**
