### PR TITLE
Populate native runtime sources

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
From dotnet/corert at commit bb212a9d2083046724f48e206f47b7dfb78d9979.

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
(`--author="dotnet-bot <dotnet-bot@microsoft.com>"` is the magic incantation to commit as dotnet-bot, for my future reference.)

**Comment by jkotas** [comment]
`src/coreclr/src/nativeaot/Runtime/coreclr/*` should not be needed.

**Comment by jkotas** [comment]
> commit as dotnet-bot

IIRC, squash&merge used to ignore this. To commit these file moves as dotnet-bot, it may work better to push them up directly to runtimelab/NativeAOT.

**Comment by MichalStrehovsky** [comment]
> IIRC, squash&merge used to ignore this. To commit these file moves as dotnet-bot, it may work better to push them up directly to runtimelab/NativeAOT.

It seems to work now. See e.g. when I ported crossgen2 over to the runtime repo: https://github.com/dotnet/runtime/commit/ac857a2e19fa42bd22ae99d12b9d9f874eba39a6

**Comment by jkotas** [comment]
Maybe it works only when author of the PR == person merging the PR. I will leave it to you to press the button.

**Comment by MichalStrehovsky** [comment]
Sigh.

image

**Pull request merged**
