### PR TITLE
[NativeAOT-LLVM] Implement `ldvirtftn` support

### PR DESCRIPTION
**Pull request by SingleAccretion**
Emit the necessary helper in the object writer.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/nativeaot-llvm

**Review by yowl — APPROVED** [review]
Looks good, thanks!

**Comment by jkotas** [comment]
@SingleAccretion Could you please resolve the conflict?

**Comment by SingleAccretion** [comment]
Conflicts have been resolved.

TLS statics test failed on OSX x64, an upstream issue I've seen in the past as well.

**Pull request merged**
