### PR TITLE
[NativeAOT-LLVM] Debug info refactoring

### PR DESCRIPTION
**Pull request by SingleAccretion**
Two changes:
1) Initialize the DI structures eagerly instead of lazily.
2) Insert a zero-offset ILOffset node so that we don't have problems with missing DI locations for calls.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/nativeaot-llvm

**Review by yowl — APPROVED** [review]
Looks good, did you try Chrome/Edge or VS (remote debugging)?  I don't see anything that would have made it stop working, just wondered?

**Comment by SingleAccretion** [comment]
> did you try Chrome/Edge or VS (remote debugging)?

I have not; will do.

**Comment by SingleAccretion** [comment]
> I have not; will do.

Done. Debugging in Chrome works, breakpoints are hit and expected source lines shown / stepped through.

**Pull request merged**
