### PR TITLE
Merge runtime/master into feature/NativeAOT

### PR DESCRIPTION
**Pull request by safern**
cc: @jkotas @MichalStrehovsky

### CODE REVIEW

**Comment by safern** [comment]
@jkotas @MichalStrehovsky there was a change in runtime/master to move the targeting TFMs to net6.0 in case you want the ILCompiler to support net5.0.

**Comment by jkotas** [comment]
Thanks for the heads up. I do not think it needs to be addressed in this PR.

**Comment by safern** [comment]
The build is failing, I guess is because of the new compilers and this code is probably not in runtime? the path contains .Corert in it.

```
src/coreclr/src/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.CoreRT.Unix.cs(23,84): error CS8902: (NETCORE_ENGINEERING_TELEMETRY=Build) 'Thread.OnThreadExit()' is attributed with 'UnmanagedCallersOnly' and cannot be converted to a delegate type. Obtain a function pointer to this method.
```

**Comment by jkotas** [comment]
I am taking care of the build breaks

**Comment by safern** [comment]
Hmm seems like we need to mark more members as unsafe:

```
src/coreclr/src/nativeaot/System.Private.CoreLib/src/System/Threading/Thread.CoreRT.Unix.cs(23,52): error CS0214: (NETCORE_ENGINEERING_TELEMETRY=Build) Pointers and fixed size buffers may only be used in an unsafe context
```

**Pull request merged**
