### PR TITLE
NativeAOT-LLVM: Merger from NativeAOT

### PR DESCRIPTION
**Pull request by yowl**
This moves forward just a few weeks, as have problems with doing too much.

### CODE REVIEW

**Comment by jkotas** [comment]
The CI is not running. Do you plan to take a look?

**Comment by yowl** [comment]
Is there a link to any logs or error messages?

**Comment by jkotas** [comment]
It was infrastructure problem. It is running now after closing and reopening the PR.

**Comment by jkotas** [comment]
CI is hitting build errors now

**Comment by yowl** [comment]
Sorry, Im going to leave this until I can test this locally.  I think not having .net6 installed globally is just making things difficult.

**Pull request closed without merging**
