### PR TITLE
fix samples/NativeLibrary

### PR DESCRIPTION
**Pull request by oudi**
fix stringToNewUTF8 not export & issue #2731

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please fix https://github.com/dotnet/runtimelab/blob/499133ec161709f257444a2315945f36728ecb5f/samples/HelloWorld/HelloWorld.csproj#L13-L14 as well?

**Comment by yowl** [comment]
Notice the jobs aren't running here or in #2736 , @jkotas, can you see an error?

**Comment by jkotas** [comment]
This is AzDo outage affecting many repos

**Comment by oudi** [comment]
@dotnet-policy-service agree

**Comment by jkotas** [comment]
@yowl nodejs is failing to install:
```
  33 |          Invoke-WebRequest -Uri "https://nodejs.org/dist/$NodeJSVersio …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |  500 Internal Server Error  500 Internal Server Error nginx   
Invoke-WebRequest: /__w/1/s/eng/pipelines/runtimelab/install-nodejs.ps1:33
```

**Comment by yowl** [comment]
The same step worked over in https://github.com/dotnet/runtimelab/pull/2736/checks?check_run_id=32226502245, probably just worth closing and reopening, a 500 error indicates a server error on the node side so hopefully it was just temporary.

**Comment by jkotas** [comment]
@yowl @SingleAccretion Does this look good?

**Review by SingleAccretion — APPROVED** [review]
This LGTM. Thank you @oudi!

**Pull request merged**
