### PR TITLE
Do not generate unused metadata

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
There are no runtime APIs to query things like custom attributes on a MemberRef. Remove them from schema. We were paying extra cost in each record to say "there are no custom attributes".

Also removing MethodImpl metadata. This is used by the runtime type system when we support metadata loading. Not something we do in NativeAOT.

Together with https://github.com/dotnet/runtimelab/pull/1577 shrinks the metadata blob by 6%.

### CODE REVIEW

**Review by jkotas — APPROVED** [review]
Nice!

**Comment by yowl** [comment]
@MichalStrehovsky do you think this will need changes in the LLVM object writer, I'm hitting a BadImageFormatException at

```
___cxa_throw (HelloWasm.js:1798)
::RhpThrowEx(void *) (main.cpp:170)
get_Assembly (RuntimeNoMetadataNamedTypeInfo.cs:37)
.ctor (ResourceManager.cs:235)
get_ResourceManager (System.SR.cs:13)
invoke_vii (HelloWasm.js:7168)
InternalGetResourceString (SR.cs:83)
invoke_vii (HelloWasm.js:7168)
GetResourceString (SR.cs:35)
get_Reflection_InsufficientMetadata_NoHelpAvailable (System.SR.cs:16)
CreateFromMetadataObject (MissingMetadataExceptionCreator.cs:81)
Create (MissingMetadataExceptionCreator.cs:26)
CreateMissingMetadataException (ReflectionDomainSetupImplementation.cs:26)
CreateMissingMetadataException (ExecutionDomain.cs:295)
get_Assembly (RuntimeNoMetadataNamedTypeInfo.cs:37)
.ctor (ResourceManager.cs:235)
get_ResourceManager (System.SR.cs:13)
invoke_vii (HelloWasm.js:7168)
InternalGetResourceString (SR.cs:83)
invoke_vii (HelloWasm.js:7168)
GetResourceString (SR.cs:35)
get_Reflection_InsufficientMetadata_EdbNeeded (System.SR.cs:18)
Create (MissingMetadataExceptionCreator.cs:25)
CreateMissingMetadataException (ReflectionDomainSetupImplementation.cs:26)
CreateMissingMetadataException (ExecutionDomain.cs:295)
get_Assembly (RuntimeNoMetadataNamedTypeInfo.cs:37)
.ctor (ResourceManager.cs:235)
get_ResourceManager (System.SR.cs:13)
invoke_vii (HelloWasm.js:7168)
InternalGetResourceString (SR.cs:83)
invoke_vii (HelloWasm.js:7168)
GetResourceString (SR.cs:35)
get_Reflection_InsufficientMetadata_EdbNeeded (System.SR.cs:18)
Create (MissingMetadataExceptionCreator.cs:25)
CreateMissingMetadataException (ReflectionDomainSetupImplementation.cs:26)
CreateMissingMetadataException (ExecutionDomain.cs:295)
get_Assembly (RuntimeNoMetadataNamedTypeInfo.cs:37)
.ctor (ResourceManager.cs:235)
get_ResourceManager (System.SR.cs:13)
invoke_vii (HelloWasm.js:7168)
InternalGetResourceString (SR.cs:83)
invoke_vii (HelloWasm.js:7168)
GetResourceString (SR.cs:35)
get_DebugAssertBanner (System.SR.cs:1086)
WriteAssert (DebugProvider.cs:42)
Fail (DebugProvider.cs:29)
Fail (Debug.cs:134)
Assert (Debug.cs:99)
Assert (Debug.cs:83)
ThrowBadImageFormatException (NativeFormatReader.cs:20)
SkipInteger (NativeFormatReader.cs:213)
SkipInteger (NativeFormatReader.cs:354)
Read (MdBinaryReaderGen.cs:896)
GetTypeDefinition (NativeFormatReaderGen.cs:10861)
GetTypeDefinition (NativeFormatReaderGen.cs:7434)
invoke_vii (HelloWasm.js:7168)
UncachedGetTypeCoreCaseSensitive (NativeFormatRuntimeAssembly.GetTypeCore.CaseSensitive.cs:48)
Factory (RuntimeAssembly.cs:336)
GetOrAdd (ConcurrentUnifier.cs:113)
GetTypeCoreCaseSensitive (RuntimeAssembly.cs:252)
GetTypeCore (RuntimeAssembly.cs:203)
GetTypeCore (Helpers.cs:108)
<CreateCoreTypeResolver>b__0 (ExecutionDomain.cs:89)
$S_P_Reflection_Core_System_Reflection_Runtime_TypeParsing_CoreTypeResolver__Invoke (HelloWasm.wasm:0xd4801d)
CoreResolveType (GetTypeOptions.cs:55)
ResolveType (TypeName.cs:90)
ResolveType (TypeName.cs:56)
GetType (ExecutionDomain.cs:59)
GetType (ReflectionExecutionDomainCallbacksImplementation.cs:41)
ExtensibleGetType (ReflectionHelpers.cs:28)
GetType (ReflectionHelpers.cs:21)
$Internal_CompilerGenerated__Module___GetType_3_System_Private_CoreLib__Version_7_0_0_0__Culture_neutral__PublicKeyToken_7cec85d7bea7798e (HelloWasm.wasm:0xc06b0a)
GetType (Type.CoreRT.cs:68)
TestMetaData (HelloWasm.cs:1341)
Main (HelloWasm.cs:38)
$HelloWasm__Module___MainMethodWrapper (HelloWasm.wasm:0xc5c5fd)
$StartupCodeMain (HelloWasm.wasm:0x4af8a9)
$__managed__Main (HelloWasm.wasm:0xb89c5f)
__main_argc_argv (main.cpp:259)
(anonymous) (HelloWasm.js:1223)
callMain (HelloWasm.js:8002)
doRun (HelloWasm.js:8056)
(anonymous) (HelloWasm.js:8067)
setTimeout (async)
run (HelloWasm.js:8063)
runCaller (HelloWasm.js:7979)
removeRunDependency (HelloWasm.js:1144)
receiveInstance (HelloWasm.js:1311)
receiveInstantiationResult (HelloWasm.js:1329)
Promise.then (async)
(anonymous) (HelloWasm.js:1370)
Promise.then (async)
instantiateAsync (HelloWasm.js:1362)
createWasm (HelloWasm.js:1399)
(anonymous) (HelloWasm.js:6927)
```

Thanks.

**Comment by yowl** [comment]
Should say I don't know that it is this PR.  Just asking in case you remember.

**Comment by yowl** [comment]
Ok, its not this , its the merge from upstream just before.

**Pull request merged**
