### PR TITLE
Add official build support to native aot branch

### PR DESCRIPTION
**Pull request by safern**
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=845817&view=results

cc: @jkotas @MichalStrehovsky

### CODE REVIEW

**Comment by safern** [comment]
We will need to bring this change in as well: https://github.com/dotnet/runtimelab/pull/156

**Review by jkotas — APPROVED** [review]

**Comment by safern** [comment]
Validated against the latest official build I tested and it correctly signed and publish to artifacts the expected packages:
image

**Comment by safern** [comment]
So finally I was able to get a green official build with signed packages:

https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-experimental&package=Microsoft.DotNet.ILCompiler&protocolType=NuGet&version=6.0.0-alpha.1.20508.8&view=overview

🎉

**Comment by MichalStrehovsky** [comment]
IT'S ALIVE!

```
Microsoft Windows [Version 10.0.19041.508]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\hw>type HelloWorld.csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5</TargetFramework>
    <RestoreSources>
      https://api.nuget.org/v3/index.json;
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json;
    </RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.ILCompiler" Version="6.0.0-alpha.*" />
  </ItemGroup>

</Project>

C:\hw>type Program.cs
using System;

Console.WriteLine("Hello World!");

C:\hw>set DOTNET_ROOT=c:\git\runtime\.dotnet

C:\hw>set PATH=c:\git\runtime\.dotnet;%PATH%

C:\hw>dotnet publish -r win-x64 -c release
Microsoft (R) Build Engine version 16.8.0-preview-20451-02+51a1071f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\hw\HelloWorld.csproj (in 1.06 sec).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  HelloWorld -> C:\hw\bin\release\net5\win-x64\HelloWorld.dll
  Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT
Runtime.lib(MiscHelpers.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(MiscHelpers.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(EHHelpers.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(EHHelpers.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(GCHelpers.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(GCHelpers.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(rheventtrace.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(rheventtrace.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(threadstore.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(threadstore.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(RuntimeInstance.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(RuntimeInstance.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(startup.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(startup.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(thread.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(thread.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(portable.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(portable.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(HandleTableHelpers.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(HandleTableHelpers.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(FinalizerHelpers.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(FinalizerHelpers.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(strongname.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(strongname.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(CachedInterfaceDispatch.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(CachedInterfaceDispatch.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(DebugEventSource.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(DebugEventSource.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(StackFrameIterator.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(StackFrameIterator.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(GCMemoryHelpers.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(GCMemoryHelpers.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gcrhenv.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gcrhenv.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(ThunksMapping.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(ThunksMapping.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(MathHelpers.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(MathHelpers.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(PalRedhawkCommon.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(PalRedhawkCommon.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gcheaputilities.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gcheaputilities.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(PalRedhawkMinWin.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(PalRedhawkMinWin.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(Crst.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(Crst.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(RWLock.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(RWLock.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(TypeManager.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(TypeManager.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(eetype.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(eetype.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(OptionalFieldsRuntime.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(OptionalFieldsRuntime.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(ObjectLayout.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(ObjectLayout.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(yieldprocessornormalized.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(yieldprocessornormalized.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(RestrictedCallouts.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(RestrictedCallouts.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(eventtrace.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(eventtrace.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(event.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(event.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(stressLog.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(stressLog.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(DebugFuncEval.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(DebugFuncEval.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(RhConfig.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(RhConfig.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(objecthandle.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(objecthandle.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(sha1.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(sha1.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(allocheap.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(allocheap.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(profheapwalkhelper.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(profheapwalkhelper.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(SyncClean.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(SyncClean.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(DebuggerHook.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(DebuggerHook.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gcrhscan.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gcrhscan.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gctoclreventsink.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gctoclreventsink.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gcload.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gcload.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gceventstatus.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gceventstatus.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(handletable.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(handletable.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(handletablecore.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(handletablecore.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gchandletable.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gchandletable.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gccommon.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gccommon.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gcenv.windows.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gcenv.windows.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gcconfig.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gcconfig.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gceewks.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gceewks.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gcwks.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gcwks.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(handletablecache.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(handletablecache.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(handletablescan.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(handletablescan.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(gcscan.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(gcscan.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
bootstrapper.lib(main.obj) : warning LNK4099: PDB 'bootstrapper.pdb' was not found with 'bootstrapper.lib(main.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\bootstrapper.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
Runtime.lib(CoffNativeCodeManager.obj) : warning LNK4099: PDB 'Runtime.pdb' was not found with 'Runtime.lib(CoffNativeCodeManager.obj)' or at 'C:\hw\bin\release\net5\win-x64\native\Runtime.pdb'; linking object as if no debug info [C:\hw\HelloWorld.csproj]
  HelloWorld -> C:\hw\bin\release\net5\win-x64\publish\

C:\hw>C:\hw\bin\release\net5\win-x64\publish\HelloWorld.exe
Hello World!

C:\hw>
```

**Comment by MichalStrehovsky** [comment]
The warnings are a bug that I know how to fix.

The fact that we need to put the specific dotnet from the git repo into path is also a bug that should be fixed by publishing the tool as self-contained. I haven't figured out how to do that yet.

**Pull request merged**
