### PR TITLE
[NativeAOT-LLVM] Update nativeaot.md with advisory for EMCC_DEBUG

### PR DESCRIPTION
**Pull request by yowl**
You cannoy `set EMCC_DEBUG=1` when building.  This is not new with the recent changes, the restriction existed before.  Just worth mentioning I think.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
What are the reproduction steps for the problem? Naively doing `./build nativeaot -os Browser` does succeed (as does `./build libs.native -os Browser`) - maybe we can fix it?

(Worth mentioning that I am using EMSDK `2.0.23`)

**Comment by yowl** [comment]
`set EMCC_DEBUG=1`
then
`build nativeaot+libs -c Debug -lc Release -a wasm -os Browser`

And it seems to get stuck
```
"E:\GitHub\runtimelab\src\libraries\Native\build-native.cmd" wasm Release outconfig net6.0-Browser-Release-wasm -os Browser
  **********************************************************************
  ** Visual Studio 2019 Developer Command Prompt v16.11.1
  ** Copyright (c) 2021 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x86_x64'
  Commencing build of native components

    Determining projects to restore...
    All projects are up-to-date for restore.
  tools.filelock:DEBUG: Attempting to acquire lock 2056396803184 on C:\Users\SCOTTW~1\AppData\Local\Temp\emscripten_temp\emscripten.lock
  tools.filelock:DEBUG: Lock 2056396803184 acquired on C:\Users\SCOTTW~1\AppData\Local\Temp\emscripten_temp\emscripten.lock
  configure: "C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_PREFIX=E:/GitHub/runtimelab/src/libraries/Native/../../../artifacts/bin/native/net6.0-Browser-Release-wasm -DCLR_CMAKE_HOST_ARCH=wasm -DCMAKE_REPO_ROOT=E:/GitHub/runtimelab/src/libraries/Native/../../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=E:/GitHub/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_REPO_ROOT=E:/GitHub/runtimelab/src/libraries/Native/../../.. -DCMAKE_BUILD_TYPE=Release --no-warn-unused-cli -G Ninja -B E:/GitHub/runtimelab/src/libraries/Native/../../../artifacts/obj/native/net6.0-Browser-Release-wasm -S E:\GitHub\runtimelab\src\libraries\Native\\Unix -DCMAKE_CROSSCOMPILING_EMULATOR="E:/GitHub/emsdk/node/14.15.5_64bit/bin/node.exe"
  Not searching for unused variables given on the command line.
```
Python is running, but not clocking much time, suggesting its stuck in an emcc script trying to get the version:

From ProcExp:

"E:\GitHub\emsdk\python\3.9.2-1_64bit\python.exe"  "E:\GitHub\emsdk\upstream\emscripten\\emcc.py" -v

image

`emcc -v` does run from the command line

```
E:\GitHub\runtimelab>emcc -v
tools.filelock:DEBUG: Attempting to acquire lock 2363042171728 on C:\Users\SCOTTW~1\AppData\Local\Temp\emscripten_temp\emscripten.lock
tools.filelock:DEBUG: Lock 2363042171728 acquired on C:\Users\SCOTTW~1\AppData\Local\Temp\emscripten_temp\emscripten.lock
emcc:WARNING: invocation: E:\GitHub\emsdk\upstream\emscripten\\emcc.py -v  (in E:\GitHub\runtimelab)
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 2.0.13
clang version 13.0.0 (Cswircachegitchromium.googlesource.com-external-github.com-llvm-llvm--project 8d7cbcf582c5c7bc08a9de7f31fed63bf2687127)
Target: wasm32-unknown-emscripten
Thread model: posix
InstalledDir: E:/GitHub/emsdk/upstream/bin
shared:DEBUG: executed E:/GitHub/emsdk/upstream/bin\clang.exe -v -target wasm32-unknown-emscripten
emcc:DEBUG: total time: 2.44 seconds
tools.filelock:DEBUG: Attempting to release lock 2363042171728 on C:\Users\SCOTTW~1\AppData\Local\Temp\emscripten_temp\emscripten.lock
tools.filelock:DEBUG: Lock 2363042171728 released on C:\Users\SCOTTW~1\AppData\Local\Temp\emscripten_temp\emscripten.lock
```
I'm on an older version

**Comment by yowl** [comment]
Curiously, if you unset `EMCC_DEBUG` and try again it fails with 
```
  "E:\GitHub\runtimelab\src\libraries\Native\build-native.cmd" wasm Release outconfig net6.0-Browser-Release-wasm -os Browser
  **********************************************************************
  ** Visual Studio 2019 Developer Command Prompt v16.11.1
  ** Copyright (c) 2021 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x86_x64'
  Commencing build of native components

    Determining projects to restore...
    All projects are up-to-date for restore.
  The CMake command line is the same as the last run. Skipping running CMake.
  The parameter is incorrect
EXEC : CMake error : Generator: execution of make failed. Make command was:  install && [E:\GitHub\runtimelab\src\libraries\Native\build-native.proj]
  Failed to generate native component build project!
```

**Comment by SingleAccretion** [comment]
I see, thank you. Will try to reproduce.
> `wasm Release outconfig net6.0-Browser-Release-wasm -os Browser`

Looks a bit broken as the script doesn't use the `-os` syntax. Doesn't matter a lot though (the relevant things are unused anyway). Edit: heh, well, this is of course because of the difference in `.cmd` and `.sh` scripts.

Will take a bit closer look at this.

**Comment by SingleAccretion** [comment]
> Curiously, if you unset EMCC_DEBUG and try again it fails with

FWIW, this is a hole in `gen-buildsys.cmd`'s support for not rerunning CMake configure if the command line has not changed (it will always eagerly save the command line, and subsequently find it, regardless of anything in between save the deletion of the file it creates). Looks like https://github.com/dotnet/runtime/issues/60838 hit the same problem recently.

**Comment by jkotas** [comment]
Is this good to merge, or would you like to tweak it further based on the discussion?

**Review by SingleAccretion — APPROVED** [review]
While I was not able to reproduce the hang, adding a note so that people are aware of the possibility seems like a good idea.

**Pull request merged**
