### PR TITLE
Merge from dotnet/runtime

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
Failure is:
```
2020-11-16T01:24:59.6213328Z   System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
2020-11-16T01:24:59.6248760Z      at System.Collections.Generic.List`1.get_Item(Int32 index)
2020-11-16T01:24:59.6324963Z      at ILCompiler.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodIL callingMethodBody, MethodDesc calledMethod, ILOpcode operation, Int32 offset, ValueNodeList methodParams, ValueNode& methodReturnValue) in /_/src/coreclr/src/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/ReflectionMethodBodyScanner.cs:line 961
2020-11-16T01:24:59.6337427Z      at ILCompiler.Dataflow.MethodBodyScanner.HandleCall(MethodIL callingMethodBody, ILOpcode opcode, Int32 offset, MethodDesc calledMethod, Stack`1 currentStack) in /_/src/coreclr/src/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/MethodBodyScanner.cs:line 898
2020-11-16T01:24:59.6345216Z      at ILCompiler.Dataflow.MethodBodyScanner.Scan(MethodIL methodBody) in /_/src/coreclr/src/tools/aot/ILCompiler.Compiler/Compiler/Dataflow/MethodBodyScanner.cs:line 606
2020-11-16T01:24:59.6348156Z   Generating compatible native code. To optimize for size or speed, visit https://aka.ms/OptimizeCoreRT
```
@MichalStrehovsky Could you please take a look?

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky Could you please take a look?


Ah, in DataContractSerialization. That looks very much like mono/linker#1621.

Let me try to refresh the analyzer from the linker repo and see if that goes away.

**Comment by MichalStrehovsky** [comment]
The runtimelab check failure looks like some GitHub CI confusion because it takes me to the old build.

https://dev.azure.com/dnceng/public/_build/results?buildId=887365&view=results is the current build result and that one looks green.

**Comment by jkoritzinsky** [comment]
Package changes look good to me.

**Pull request merged**
