### PR TITLE
Reenable most tests on s390x

### PR DESCRIPTION
**Pull request by akoeplinger**

### CODE REVIEW

**Comment by akoeplinger** [comment]
Looks like we have about 300 test failures out of 70k test. Neale told me they have still a few more patches to clean up and send to get to their 100% pass rate.

**Comment by akoeplinger** [comment]
Looks like System.IO.Tests failed:

```
/home/helixbot/work/ABB8094A/p/dotnet exec --runtimeconfig System.IO.Tests.runtimeconfig.json --depsfile System.IO.Tests.deps.json xunit.console.dll System.IO.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================
~/work/ABB8094A/w/AF06097B/e ~/work/ABB8094A/w/AF06097B/e
  Discovering: System.IO.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.Tests (found 669 of 672 test cases)
  Starting:    System.IO.Tests (parallel test collections = on, max threads = 2)
./RunTests.sh: line 162: 63150 Killed                  "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.IO.Tests.runtimeconfig.json --depsfile System.IO.Tests.deps.json xunit.console.dll System.IO.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
~/work/ABB8094A/w/AF06097B/e
----- end Tue 30 Mar 2021 08:43:20 AM EDT ----- exit code 137 ----------------------------------------------------------
exit code 137 means SIGKILL Killed eg by kill
```

@uweigand have you seen this at all? might be a flaky issue.

**Comment by uweigand** [comment]
@akoeplinger No I haven't seen that before.  SIGKILL may be the out-of-memory killer, is the syslog from the build machine available somewhere?  Do you know what memory size the machine has? (Otherwise I'll find out from our team.)

**Comment by uweigand** [comment]
Ah, I found the helix log myself.  Yes, this was indeed the OOM killer:
```
[809878.573746] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/helix.service,task=dotnet,pid=63150,uid=1003
[809878.573767] Out of memory: Killed process 63150 (dotnet) total-vm:9454048kB, anon-rss:2648032kB, file-rss:2244kB, shmem-rss:0kB, UID:1003 pgtables:6326kB oom_score_adj:0
[809879.049644] oom_reaper: reaped process 63150 (dotnet), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

```

Looks like the machine has 4 GB of memory, which seems a little on the small side.

**Comment by akoeplinger** [comment]
Hm I don't know, @directhex should have access

**Comment by uweigand** [comment]
@akoeplinger I've asked the team to bump up the memory size on your builder machine.   For now, maybe you can just retry?  It seems the test case usually worked, so there may be some race condition involved as well (e.g. what else happens to be running at the same time).

**Comment by akoeplinger** [comment]
Yup, I'll just merge the PR and we can see whether it keeps happening :)

**Pull request merged**
