### PR TITLE
Merge from dotnet/runtime

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by hez2010** [comment]
Will this bump ilc version to 7.0.0-*?

**Comment by jkotas** [comment]
> Will this bump ilc version to 7.0.0-*?

Yes, it is a good candidate for #1241

**Comment by MichalStrehovsky** [comment]
Let's update the docs and add a record to the breaking changes issue once such NuGet package is out.

**Comment by jkotas** [comment]
I was wrong about that this will bump ilc version. The ilc version is still 6.0 even after this PR.

**Comment by hez2010** [comment]
I think the ilc version has been bumped to 7.0.0-*
image

**Comment by jkotas** [comment]
Ah, your right. I have looked in the wrong place.

**Pull request merged**
