### PR TITLE
Optimize away unused virtual implementations on abstract classes

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
This change lets us optimize away virtual method bodies on abstract classes that are overriden in all derived classes.

E.g.

```csharp
class Base
{
    public virtual void DoSomething() => CallExpensiveMethod();
}

class Derived : Base
{
    public override void DoSomething() => SomeOtherMethod();
}
```

We shouldn't need to generate `Base.DoSomething` above since nobody calls that.

The optimization reuses the tentative instance methods introduced last week - the first commit just extracts that into a reusable component. The second commit makes us consider references to virtual method on abstract classes tentative, until e.g. a derived class that uses the base implementation makes them not tentative anymore.

We would probably get more bang if we could this to non-abstract classes too, but it's pretty difficult to discern "constructed EEType that is only constructed because it's a base of an allocated type". The biggest complication is reflection.

### CODE REVIEW

**Comment by jkotas** [comment]
I would be fine with this. If we have the capability, we can also use it where possible - even it means just 0.6% for what you have measured.

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by MichalStrehovsky** [comment]
Who disabled "rebase and merge" and for what reason? Sigh. Merge commit it is.

**Comment by jkotas** [comment]
I was asked to disable it to match dotnet/runtime.

**Comment by MichalStrehovsky** [comment]
> I was asked to disable it to match dotnet/runtime.

Sigh. I remember that issue in the runtime repo and it didn't make sense to me at that time and it doesn't make sense to me today after re-reading it either. Yay for consistency.

**Pull request merged**
