### PR TITLE
NativeAOT-LLVM: Merge to mid dec

### PR DESCRIPTION
**Pull request by yowl**
I did try to merge to the end of NativeAOT but got bogged down in errors so will do some baby steps.

### CODE REVIEW

**Comment by jkotas** [comment]
> runtimelab (Build Build Linux_musl x64 Release) Cancelled after 1m

This seems to be infrastructure problem triggered by the earlier merge conflicts in the yaml files. It should go away on rerun.

**Comment by yowl** [comment]
The only non-merge change here is setting the test host to Windows for `TargeArchitecture == wasm`

**Comment by yowl** [comment]
cc @SingleAccretion

**Review by SingleAccretion — APPROVED** [review]
LGTM!

**Pull request merged**
