### PR TITLE
Adding Official Build Support for runtimelab

### PR DESCRIPTION
**Pull request by joperezr**
cc: @safern 
FYI: @jkotas @layomia 

This will add official build support to Utf8String in runtimelab repo. Packages will be published to our dotnet experimental feed every time we get a new PR merged. Once this is ready and goes in, I will port these changes over to dotnet/runtime repo so that other experiment branches can benefit from it too.

@safern make sure that you disable whitespace diff when checking the changes as most of the lines that were changed in the yml is only because I had to indent them.

### CODE REVIEW

**Comment by safern** [comment]
The only concern I have is what we spoke offline with regard full platform manifest, but I believe we can live without it for a couple of weeks as @jkoritzinsky is close on getting his change done to do it from a static list instead of a dinámica set of files.

**Comment by ericstj** [comment]
@safern can you pick this up now that @joperezr is out?

**Comment by safern** [comment]
> @safern can you pick this up now that @joperezr is out?

Sure.

**Comment by ericstj** [comment]
We should also consider how we might enable builds for non-forked dotnet/runtime repos.  I see https://github.com/dotnet/runtimelab/tree/DllImportGenerator has no CI nor build support.

**Comment by safern** [comment]
Why not make all experiments instead fork from `dotnet/runtime` -- that would simplify things infrastructure wise.

**Comment by ericstj** [comment]
I think that's very undesirable for single-standalone libraries.  Building the entire runtime is pretty expensive, cloning and dealing with codeflow is as well.  I guess if we aren't going to create a pattern for single libraries we should keep corefxlab around for those.  Thoughts @jkotas?

**Comment by jkotas** [comment]
If there is enough single libraries experiments, I agree it makes sense to have a template optimized for them.

The pattern for single libraries will need maintenance independent on whether it is in runtimelab or corefxlab. I do not think we would save anything in the long-run by keeping corefxlab alive for single libraries.

> Building the entire runtime is pretty expensive, cloning and dealing with codeflow is as well.

Yes and it is a problem for dotnet/runtime too where it affects a lot more people than it would affect in dotnet/runtimelab. Another option may be to just keep improving leaf-library development experience in dotnet/runtime.

> I see https://github.com/dotnet/runtimelab/tree/DllImportGenerator has no CI nor build support.

I expect that the DllImportGenerator will eventually need to start adding public runtime APIs to make progress and turn into a dotnet/runtime fork.

**Comment by ericstj** [comment]
Let's carry this discussion on over in https://github.com/dotnet/runtimelab/issues/88.

**Comment by safern** [comment]
Sounds good to me. I'll finish the regular support this week, and we can discuss the single libraries support.

**Comment by safern** [comment]
@jkotas this is now ready. Here is the test official build:
https://dnceng.visualstudio.com/internal/_build/results?buildId=840458&view=results

Pending to add support for a standalone experiment.

**Comment by jkotas** [comment]
Nice! What is the nuget feed that the package is published to?

**Comment by safern** [comment]
So the runtimelab official builds will be published into: https://dnceng.visualstudio.com/public/_packaging?_a=feed&feed=dotnet-experimental

However this test official build didn't published because I didn't add the `DARC` default channel map to the branch I created the official build from. I will be adding this map for all `feature/*` branches. However, you can look at the artifacts that we would have published here: https://dnceng.visualstudio.com/internal/_build/results?buildId=840458&view=artifacts&type=publishedArtifacts -- the artifact name is `PackageArtifacts`.

Do you want me to setup a test map from this branch and queue another build so that packages are published to the experiment feed?

**Comment by jkotas** [comment]
> Do you want me to setup a test map from this branch and queue another build so that packages are published to the experiment feed?

I do not think it is needed. You can rather spend time on doing the permanent setup. Eventually, I want to test referencing the experimental runtime package from a hello world project and see it work end-to-end.

**Pull request merged**
