### PR TITLE
[NativeAOT-LLVM] Implement WASH-EH-based exception dispatch

### LINKED ISSUE #1983: NativeAOT-LLVM: support wasm exceptions
We should support wasm-exceptions instead of exceptions through javascript (Emscripten exceptions).  This will allow exception support in non javascript hosts and should make the code a bit smaller.
This C++
```cpp
#include <stdio.h>

void throws()
{
  throw 1;
}

int main() {
  try {
    throws();
  } catch(...) {
    puts("catch!");
  }
  return 0;
}

```

Goes to this LLVM as a guide
```ll

@_ZTIi = external constant ptr
@.str = private unnamed_addr constant [7 x i8] c"catch!\00", align 1, !dbg !0

define dso_local void @_Z6throwsv() #0 !dbg !19 {
  %1 = call ptr @__cxa_allocate_exception(i64 4) #2, !dbg !23
  store i32 1, ptr %1, align 16, !dbg !23
  call void @__cxa_throw(ptr %1, ptr @_ZTIi, ptr null) #5, !dbg !23
  unreachable, !dbg !23
}

declare ptr @__cxa_allocate_exception(i64)

declare void @__cxa_throw(ptr, ptr, ptr)

define dso_local noundef i32 @main() #1 personality ptr @__gxx_wasm_personality_v0 !dbg !24 {
  %1 = alloca i32, align 4
  %2 = alloca ptr, align 8
  store i32 0, ptr %1, align 4
  invoke void @_Z6throwsv()
          to label %15 unwind label %3, !dbg !28

3:                                                ; preds = %0
  %4 = catchswitch within none [label %5] unwind to caller, !dbg !30

5:                                                ; preds = %3
  %6 = catchpad within %4 [ptr null], !dbg !30
  %7 = call ptr @llvm.wasm.get.exception(token %6), !dbg !30
  store ptr %7, ptr %2, align 8, !dbg !30
  %8 = call i32 @llvm.wasm.get.ehselector(token %6), !dbg !30
  br label %9, !dbg !30

9:                                                ; preds = %5
  %10 = load ptr, ptr %2, align 8, !dbg !30
  %11 = call ptr @__cxa_begin_catch(ptr %10) #2 [ "funclet"(token %6) ], !dbg !30
  %12 = invoke i32 @puts(ptr noundef @.str) [ "funclet"(token %6) ]
          to label %13 unwind label %16, !dbg !31

13:                                               ; preds = %9
  call void @__cxa_end_catch() [ "funclet"(token %6) ], !dbg !33
  br label %14, !dbg !33

14:                                               ; preds = %13, %15
  ret i32 0, !dbg !34

15:                                               ; preds = %0
  br label %14, !dbg !30

16:                                               ; preds = %9
  %17 = cleanuppad within %6 [], !dbg !33
  invoke void @__cxa_end_catch() [ "funclet"(token %17) ]
          to label %18 unwind label %19, !dbg !33

18:                                               ; preds = %16
  cleanupret from %17 unwind to caller, !dbg !33

19:                                               ; preds = %16
  %20 = cleanuppad within %17 [], !dbg !33
  call void @_ZSt9terminatev() #6 [ "funclet"(token %20) ], !dbg !33
  unreachable, !dbg !33
}

declare i32 @__gxx_wasm_personality_v0(...)
declare ptr @llvm.wasm.get.exception(token) #2
declare i32 @llvm.wasm.get.ehselector(token) #2
declare i32 @llvm.eh.typeid.for(ptr) #3
declare ptr @__cxa_begin_catch(ptr)
declare i32 @puts(ptr noundef) #4
declare void @__cxa_end_catch()
declare void @_ZSt9terminatev()
```
https://godbolt.org/ can be used to try other C++ examples with the options `-S -emit-llvm -fwasm-exceptions`

### PR DESCRIPTION
**Pull request by SingleAccretion**
This change implements WASM-EH-based exception dispatch and makes it the default for browser targets.

Notable changes:
1) Dispatch codegen strategy was changed to have one dispatch switch per one logical protected region. The universal switch strategy was hitting [LLVM bugs](https://github.com/llvm/llvm-project/issues/62961), and in general, I would expect this flow configuration to lower better to WASM, which, recall, has scoped exception handling regions, so jumping out of a catch and into a try requires some unnatural flow alterations.
2) We now build two new static libraries as part of the native runtime build, one that uses the C++-based dispatch and one that uses WASM EH. These implement differences between the two ABIs at the dispatcher level. The libraries are bundled into the runtime package and one is selected for link based on the value of `WasmEnableExceptionHandling`.
3) `WasmEnableExceptionHandling` is set to `true` by default for browser targets. However, the compiler (i. e. ILC) treats it as `false` by default, since the C++-based solution is notionally more compatible. A `--codegenopt:LlvmExceptionHandlingModel=[wasm|cpp]` switch is introduced to control the EH model at the compiler level.
4) NodeJS v18 is installed in CI for testing, as v14 that we have so far been using is too old.
5) A new `ExceptionHandlingTests.Cpp` test has been introduced that sets `WasmEnableExceptionHandling` to `false`, with some of the test code shared between it and `HelloWasm`.

Closes #1983.
Contributes to #2169.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/nativeaot-llvm

**Comment by SingleAccretion** [comment]
WASM code looks good with this change. Some dispatch samples:

1\) From `TestTryCatchThrowException`
```
 127e80: 07 00                      | catch 0
 127e82: 21 04                      |   local.set 4
 127e84: 20 01                      |   local.get 1
 127e86: 24 00                      |   global.set 0 <__stack_pointer>
 127e88: 02 40                      |   block
 127e8a: 20 03                      |     local.get 3
 127e8c: 20 00                      |     local.get 0
 127e8e: 20 04                      |     local.get 4
 127e90: 41 eb 02                   |     i32.const 363
 127e93: 41 cc 9e 3b                |     i32.const 970572
 127e97: 10 b6 06                   |     call 822 <RhpDispatchHandleExceptionWasmCatch>
 127e9a: 0d 00                      |     br_if 0
 127e9c: 09 01                      |     rethrow 1
 127e9e: 0b                         |   end

Total dispatch cost (single catch): ~30 bytes.
```
2\) From `TestCatchExceptionType`:
```
 12808b: 07 00                      | catch 0
 12808d: 21 05                      |   local.set 5
 12808f: 20 01                      |   local.get 1
 128091: 24 00                      |   global.set 0 <__stack_pointer>
 128093: 02 40                      |   block
 128095: 02 40                      |     block
 128097: 02 40                      |       block
 128099: 02 40                      |         block
 12809b: 02 40                      |           block
 12809d: 20 04                      |             local.get 4
 12809f: 20 00                      |             local.get 0
 1280a1: 20 05                      |             local.get 5
 1280a3: 41 b4 83 02                |             i32.const 33204
 1280a7: 10 b4 06                   |             call 820 <RhpDispatchHandleExceptionWasmMutuallyProtectingCatches>
 1280aa: 0e 04 00 01 02 03 00       |             br_table 0 1 2 3 0
 1280b1: 0b                         |           end
 1280b2: 09 04                      |           rethrow 4
 1280b4: 0b                         |         end
 1280b5: 0c 02                      |         br 2
 1280b7: 0b                         |       end
 1280b8: 0c 01                      |       br 1
 1280ba: 0b                         |     end
 1280bb: 0b                         |   end

Total dispatch cost (mutually protecting handlers): ~50 bytes.
```
3\) From `TryFinallyWithCatch`:
```
 147b74: 07 00                      | catch 0
 147b76: 21 02                      |   local.set 2
 147b78: 20 01                      |   local.get 1
 147b7a: 24 00                      |   global.set 0 <__stack_pointer>
 147b7c: 20 00                      |   local.get 0
 147b7e: 20 02                      |   local.get 2
 147b80: 41 89 04                   |   i32.const 521
 147b83: 10 b7 06                   |   call 823 <RhpDispatchHandleExceptionWasmFault>
 147b86: 09 00                      |   rethrow 0
 147b88: 0b                         | end

Total dispatch cost (fault): ~20 bytes.
```

Some optimization ideas:
1\) Top-level dispatch can calculate the original stack using the passed-in shadow one, provided it knows the shadow frame size. We could encode the latter as part of some other argument, e. g. for mutually-protecting case - into the table, others - together with the handler.
2\) If we could somehow guarantee the numerical order for handler and filter funclets (like, say `filter` == `handler - 1`), we could only pass one of them. This would likely require a new LLVM feature, however.

That said, these will not be very impactful - we already get close to ideal codegen.

**Comment by SingleAccretion** [comment]
Some preliminary dispatch benchmarks:
```scala
; NativeAOT, WASM EH, Chrome
Bench_UnwindWithCatch<50>(depth: 2000) took: 149 ms
Bench_UnwindWithFault<50>(depth: 2000) took: 139 ms
Bench_ThrowCatch<200>(depth: 125) took: 843 ms
Bench_Rethrow<200>(depth: 125) took: 197 ms

; NativeAOT, WASM EH, NodeJS
Bench_UnwindWithCatch<50>(depth: 2000) took: 286 ms
Bench_UnwindWithFault<50>(depth: 2000) took: 274 ms
Bench_ThrowCatch<200>(depth: 125) took: 14417 ms
Bench_Rethrow<200>(depth: 125) took: 405 ms

; CoreCLR, Windows x64
Bench_UnwindWithCatch<50>(depth: 2000) took: 154 ms
Bench_UnwindWithFault<50>(depth: 2000) took: 156 ms
Bench_ThrowCatch<200>(depth: 125) took: 477 ms
Bench_Rethrow<200>(depth: 125) took: 450 ms

; NativeAOT, Windows x64
Bench_UnwindWithCatch<50>(depth: 2000) took: 36 ms
Bench_UnwindWithFault<50>(depth: 2000) took: 38 ms
Bench_ThrowCatch<200>(depth: 125) took: 39 ms
Bench_Rethrow<200>(depth: 125) took: 36 ms

; Mono WASM, AOT
Bench_UnwindWithCatch<50>(depth: 2000) took: 1000 ms
Bench_UnwindWithFault<50>(depth: 2000) took: 287 ms
Bench_ThrowCatch<200>(depth: 125) took: 396 ms
Bench_Rethrow<200>(depth: 125) took: 915 ms

; Mono WASM, default (interpreter)
Bench_UnwindWithCatch<50>(depth: 2000) took: 116 ms
Bench_UnwindWithFault<50>(depth: 2000) took: 84 ms
Bench_ThrowCatch<200>(depth: 125) took: 92 ms
Bench_Rethrow<200>(depth: 125) took: 554 ms
```
<details>

```cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Threading;
using System.Diagnostics;

public class Benchmarks
{
    private static long s_startTimeStamp;
    private static string s_currentBenchName;

    public static int Main()
    {
        Bench_UnwindWithCatch();
        Bench_UnwindWithFault();
        Bench_ThrowCatch();
        Bench_Rethrow();
        return 100;
    }

    private static void Bench_UnwindWithCatch()
    {
        static void Bench_UnwindWithCatchRecursive(int depth)
        {
            if (depth == 0)
            {
                throw new BenchException();
            }

            try
            {
                Bench_UnwindWithCatchRecursive(depth - 1);
            }
            catch (NullReferenceException) { }
        }

        const int UnwindDepth = 2000;
        const int RepeatCount = 50;

        StartBench($"Bench_UnwindWithCatch<{RepeatCount}>(depth: {UnwindDepth})");
        for (int i = 0; i < RepeatCount; i++)
        {
            try
            {
                Bench_UnwindWithCatchRecursive(UnwindDepth);
            }
            catch { }
        }
        EndBench();
    }

    private static void Bench_UnwindWithFault()
    {
        static void Bench_UnwindWithFaultRecursive(int depth)
        {
            if (depth == 0)
            {
                throw new BenchException();
            }

            try
            {
                Bench_UnwindWithFaultRecursive(depth - 1);
            }
            finally
            {
                int x = 0;
                Volatile.Write(ref x, 0);
            }
        }

        const int UnwindDepth = 2000;
        const int RepeatCount = 50;

        StartBench($"Bench_UnwindWithFault<{RepeatCount}>(depth: {UnwindDepth})");
        for (int i = 0; i < RepeatCount; i++)
        {
            try
            {
                Bench_UnwindWithFaultRecursive(UnwindDepth);
            }
            catch { }
        }
        EndBench();
    }

    private static void Bench_ThrowCatch()
    {
        static void Bench_ThrowCatchRecursive(int depth)
        {
            if (depth == 0)
            {
                throw new BenchException();
            }

            try
            {
                Bench_ThrowCatchRecursive(depth - 1);
            }
            catch (BenchException)
            {
                throw new BenchException();
            }
        }

        const int UnwindDepth = 125;
        const int RepeatCount = 200;

        StartBench($"Bench_ThrowCatch<{RepeatCount}>(depth: {UnwindDepth})");
        for (int i = 0; i < RepeatCount; i++)
        {
            try
            {
                Bench_ThrowCatchRecursive(UnwindDepth);
            }
            catch { }
        }
        EndBench();
    }

    private static void Bench_Rethrow()
    {
        static void Bench_RethrowRecursive(int depth)
        {
            if (depth == 0)
            {
                throw new BenchException();
            }

            try
            {
                Bench_RethrowRecursive(depth - 1);
            }
            catch { throw; }
        }

        const int UnwindDepth = 125;
        const int RepeatCount = 200;

        StartBench($"Bench_Rethrow<{RepeatCount}>(depth: {UnwindDepth})");
        for (int i = 0; i < RepeatCount; i++)
        {
            try
            {
                Bench_RethrowRecursive(UnwindDepth);
            }
            catch { }
        }
        EndBench();
    }    

    private static void StartBench(string name)
    {
        s_currentBenchName = name;
        s_startTimeStamp = Stopwatch.GetTimestamp();
    }

    private static void EndBench()
    {
        TimeSpan elapsed = Stopwatch.GetElapsedTime(s_startTimeStamp);
        Console.WriteLine($"{s_currentBenchName} took: {elapsed.TotalMilliseconds:0} ms");
    }
}

public class BenchException : Exception { }
```
</details>

Overall looking competitive with CoreCLR, but, of course, rather behind desktop NAOT (and somewhat interestingly Mono as well), so there is clearly room for improvement. One obvious performance bug is that on Node `Bench_ThrowCatch` is very slow due to `emscripten_get_callstack`. Another performance anomaly I discovered is the unwind implementation in Firefox - so slow it did not make it into the list.

**Review by yowl — APPROVED** [review]
Youve' got a much better handle on this than I do.  Tests and codegen looks good.  Thanks!

**Pull request merged**
