### PR TITLE
[NativeAOT-LLVM] Merge to Jul 10

### PR DESCRIPTION
**Pull request by SingleAccretion**
To help with our WASI P2 efforts. Note this merge _does not_ include the WASI P2 commits themselves.

Mostly no significant changes in this merge, just some usual churn. One exception is a bug fix for the case of a non-empty export list for an executable on `browser`.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/nativeaot-llvm, @yowl

**Review by yowl — APPROVED** [review]
Thanks for doing this one, looks all good!

**Comment by jkotas** [comment]
Thank you!

**Comment by pavelsavara** [comment]
thank you :)

**Pull request merged**
