### PR TITLE
Add more stackoverflow avoidance to Regex

### PR DESCRIPTION
**Pull request by stephentoub**
Olli, please let me know if there's a reason some of these aren't necessary.  I just went through this one file looking for obvious self-recursion.

### CODE REVIEW

**Comment by stephentoub** [comment]
Contributes to https://github.com/dotnet/runtimelab/issues/1537

**Comment by stephentoub** [comment]
I will close this and re-make it against dotnet/runtime once things are merged there.

**Comment by olsaarik** [comment]
@stephentoub since this PR me and Margus looked through all the algorithms and found a few more cases that needed addressing. I'll address those, so I can include both these and the new ones in a new PR.

**Comment by stephentoub** [comment]
Sounds good.  Thanks, @olsaarik.

**Pull request closed without merging**
