### PR TITLE
Adding CI coverage to NativeAOT branch

### PR DESCRIPTION
**Pull request by joperezr**
FYI: @jkotas

### CODE REVIEW

**Comment by joperezr** [comment]
Build is succeeding but looks like the new coreclr aot code is causing the coreclr build to take much longer so it has now timed out twice while trying to publish the build assets to the artifacts container. I'll go ahead and add one more change here that will increase the timeout of the product build to 90 mins (from 60) which should be more than enough to finish the Windows builds.

**Comment by jkotas** [comment]
>  new coreclr aot code

This code is not hooked up in the build yet. The build should be still identical to what is in dotnet/runtime.

**Comment by joperezr** [comment]
Oh interesting, it’s weird then that the build timed out 2/2 times, but it hasn’t timed out in other experiments but we might have just been lucky. I’ll check and if other branches are close to timing out, I’ll extend to 90 mins directly into dotnet/runtime so that it applies to all experiments

**Comment by joperezr** [comment]
Not sure why CI doesn’t show up as green yet but if you navigate to AzDO the in-progress build have actually already finished successfully so I’ll go ahead and merge this in.

**Pull request merged**
