### PR TITLE
Add MstatDump to runtimelab

### PR DESCRIPTION
**Pull request by agocke**
Source pulled from https://github.com/dotnet/runtime/pull/73913#issuecomment-1214374600 by @suchiman

### CODE REVIEW

**Comment by MichalStrehovsky** [comment]
We should use the one from https://github.com/dotnet/runtime/pull/73913#issuecomment-1214374600 (@suchiman original version).

The one in my gist has random writelines to demonstrate stuff and reads a file format version that is still not approved by anyone in the pr.

**Comment by agocke** [comment]
Updated

**Comment by agocke** [comment]
@Suchiman would you be OK with me integrating this sample into runtimelab as a starting point?

**Comment by Suchiman** [comment]
@agocke of course

**Pull request merged**
