### PR TITLE
Complete NativeAOT experiment

### PR DESCRIPTION
**Pull request by kant2002**
From what I see, everything is completed here, and all we can celebrate bright future laying ahead of us.

### CODE REVIEW

**Comment by ChristianWeyer** [comment]
Wow.
What exactly does this mean, for us mere mortals? ;-)

**Comment by kant2002** [comment]
I have no idea, but NativeAOT is part of runtime repository right now. All code moved there. I can only expect better future for that technology from now on. On practical purposes there long road to improve other technologies to make NativeAOT usage a breeze. 

I'm not Microsoft employee, and this is my personal opinion based on observable facts.

**Comment by jkotas** [comment]
Announcement: https://github.com/dotnet/runtimelab/issues/1241#issuecomment-1026571480

> What exactly does this mean, for us mere mortals? ;-)

- Switch to the new package feed
- Issues and PRs should be submitted to dotnet/runtime repo from now on

**Review by jkotas — APPROVED** [review]
Thanks!

**Pull request merged**
