### PR TITLE
Runtime ingestion

### PR DESCRIPTION
**Pull request by ericstj**
Merge dotnet/runtime@2287fe54a600d9293c1d2135c54d40f609e15472

### CODE REVIEW

**Comment by ericstj** [comment]
@joperezr -- this is still not triggering CI 😕 
/cc @safern in case he has any ideas.

**Comment by joperezr** [comment]
I tried changing something on the pipeline, let me see if Closong and reopening will cause CI to get triggered

**Comment by ericstj** [comment]
Its possible a recent change in runtime broke your CI support.   There were some changes to yml

**Comment by joperezr** [comment]
I see, in theory the way we setup the runtime yml we shouldn’t be too dependent on changes in the runtime ymls but that is totally possible. I’ll do some digging tomorrow and figure out what the problem is and fix it.

**Comment by safern** [comment]
There's merge conflicts. When there are merge conflicts CI doesn't run.

**Comment by joperezr** [comment]
We didn't have merge conflicts yesterday and CI didn't trigger, I just fixed the ones on this PR and it still doesn't trigger, I'm sure that this must be because the yml got broken by runtime changes, I'll investigate now.

**Comment by safern** [comment]
It seems like not even /azp comments are working, maybe the size of the PR is messing up AzDo?

**Comment by joperezr** [comment]
After some investigation between @safern and myself, we noticed that it does seem to be a bug with Azure Pipelines where they can't handle PRs with that many changes. I opened another PR with only 300 changes and that one did seem to work, so I'll split this PR into two ingestions in order to get CI coverage of both ingestions and get into latest runtime.

**Comment by joperezr** [comment]
Closing this one in favor of #13

**Comment by ericstj** [comment]
>  a bug with Azure Pipelines where they can't handle PRs with that many changes

Interesting.  Have we filed this bug with AzDo?

**Comment by safern** [comment]
> Interesting. Have we filed this bug with AzDo?

Not yet, but we do plan to do it.

**Comment by ericstj** [comment]
I had another random idea.  Is there an off-chance that someone used a key-phrase in a commit that was merged over that suppressed validation?  If you isolated the bug to commit / file count already then ignore me.

**Comment by joperezr** [comment]
We haven't validated it, we just feel that to be the case because of the more detailed error you and I saw last night plus the fact that a PR with fewer commits did work. Once we merge that we'll be able to validate by trying to merge the remaining commits to see if this is indeed an issue with the number of commits or instead with one particular one.

**Pull request closed without merging**
