### PR TITLE
[NativeAOT-LLVM] Merge pre10

### PR DESCRIPTION
**Pull request by yowl**
Small merge forward to help find the CI test failure, see last couple of comments.

### CODE REVIEW

**Comment by yowl** [comment]
@ericstj @jkoritzinsky I'm looking at https://github.com/dotnet/runtime/pull/107639 and wondering it is safe to merge here without merging more commits from upstream?

The current error I have here is 
```
/__w/1/s/.dotnet/sdk/9.0.100-rc.1.24452.12/Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3106: Assembly strong name "/home/cloudtest_azpcontainer/.nuget/packages/microsoft.build.framework/17.8.3/ref/net8.0/Microsoft.Build.Framework.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\). [/__w/1/s/src/tools/illink/src/ILLink.Tasks/ILLink.Tasks.csproj::TargetFramework=net9.0] [/__w/1/s/src/tests/build.proj]
/__w/1/s/.dotnet/sdk/9.0.100-rc.1.24452.12/Microsoft.Common.CurrentVersion.targets(2413,5): warning MSB3106: Assembly strong name "/home/cloudtest_azpcontainer/.nuget/packages/microsoft.build.utilities.core/17.8.3/ref/net8.0/Microsoft.Build.Utilities.Core.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those characters are Equals(=), Comma(,), Quote("), Apostrophe('), Backslash(\). [/__w/1/s/src/tools/illink/src/ILLink.Tasks/ILLink.Tasks.csproj::TargetFramework=net9.0] [/__w/1/s/src/tests/build.proj]
```
Which I think originate from 
```
    <PackageDownloadAndReference Include="Microsoft.Build.Framework" Version="$(MicrosoftBuildFrameworkVersion)" Folder="ref/net472" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net472'))" />
    <PackageDownloadAndReference Include="Microsoft.Build.Framework" Version="$(MicrosoftBuildFrameworkVersion)" Folder="ref/net8.0" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))" />
    <PackageDownloadAndReference Include="Microsoft.Build.Utilities.Core" Version="$(MicrosoftBuildUtilitiesCoreVersion)" Folder="ref/net472" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net472'))" />
    <PackageDownloadAndReference Include="Microsoft.Build.Utilities.Core" Version="$(MicrosoftBuildUtilitiesCoreVersion)" Folder="ref/net8.0" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))" />
```

**Comment by ericstj** [comment]
That's odd.  We should look at the assets file for `ILLink.Tasks.csproj`.  Seems like it's not restoring those packages.

**Comment by yowl** [comment]
Is that something I can do, where is the assets file ?

**Comment by ericstj** [comment]
I pulled down the binlog which contains this information.  For example https://artprodcus3.artifacts.visualstudio.com/A6fcc92e5-73a7-4f88-8d13-d9045b45fb27/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2RuY2VuZy1wdWJsaWMvcHJvamVjdElkL2NiYjE4MjYxLWM0OGYtNGFiYi04NjUxLThjZGNiNTQ3NDY0OS9idWlsZElkLzg1NjIwOC9hcnRpZmFjdE5hbWUvTG9nc19CdWlsZF9BdHRlbXB0MV93aW5kb3dzX194NjRfZGVidWdf0/content?format=file&subPath=%2FDebug%2FInnerManagedTestBuild.3.binlog

I do see in `D:\a\_work\1\s\artifacts\obj\ILLink.Tasks\project.assets.json` that the packages were included:
```json
"downloadDependencies": [
  {
    "name": "Microsoft.Build.Framework",
    "version": "[17.8.3, 17.8.3]"
  },
  {
    "name": "Microsoft.Build.Utilities.Core",
    "version": "[17.8.3, 17.8.3]"
  },
  {
    "name": "Microsoft.NET.ILLink.Tasks",
    "version": "[8.0.0, 8.0.0]"
  }
],
```
That same file mentions the package path is
```
"packagesPath": "D:\\a\\_work\\1\\s\\.packages\\",
```

However in the project I see the references are constructed as
image

So the problem here is that the package path is not being correctly set.  The normal way this is set is by importing the props generated by NuGet.

We can see in D:\a\_work\1\s\artifacts\obj\ILLink.Tasks\ILLink.Tasks.csproj.nuget.g.props that this is generated correctly:
```
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">D:\a\_work\1\s\.packages\</NuGetPackageRoot>
```

This is coming from C:\Users\cloudtest\.nuget\packages\microsoft.dotnet.arcade.sdk\10.0.0-beta.24467.1\tools\RepoLayout.props
https://github.com/dotnet/arcade/blob/d1bc0779143e410ec82696f9865c4eb407db8d67/src/Microsoft.DotNet.Arcade.Sdk/tools/RepoLayout.props#L10-L13

That is imported before the generated nuget props file.  So apparently there's a problem with the agreement between the package folder set during restore and that set during build.  I would have expected the Arcade targets to be in play during restore as well, but it seems that's not the case for some reason.

**Comment by yowl** [comment]
Many thanks for the detailed breakdown, I will compare with the upstream binlog to see if that reveals anything different here for the build or restore.

**Comment by ericstj** [comment]
One thing I noticed - the step that's failing is "Build tests".  This same project restores and builds successfully in the "Build product" phase.  I wonder if there's a difference between the two.

**Comment by yowl** [comment]
> One thing I noticed - the step that's failing is "Build tests". This same project restores and builds successfully in the "Build product" phase. I wonder if there's a difference between the two.

THanks yes, we were missing `-ci` in the test script, which does `_ArcadeScriptArgs="-ci"` so I'm guessing that was the key.

**Comment by yowl** [comment]
cc @dotnet/nativeaot-llvm

**Review by SingleAccretion — APPROVED** [review]
LGTM. Thank you!

**Comment by jkotas** [comment]
@ericstj Thank you for helping us to get to the bottom of the nuget build break!

**Pull request merged**
