### PR TITLE
Deleting parts of suspension-async flavor.

### PR DESCRIPTION
**Pull request by VSadov**
Deleting runtime-async related parts. They served their purpose well!! But no need to keep that code around.

### CODE REVIEW

**Comment by VSadov** [comment]
I see some test failures (as in `src/tests/run bat checked`), but I see the same failures without the change. 
I assume the failures are either preexisting or machine-specific. We can look at that later.

**Review by jakobbotsch — APPROVED** [review]

**Comment by VSadov** [comment]
Thanks!!

**Comment by jakobbotsch** [comment]
Do we want to keep the notes about the suspension-async in the design doc, or should it be removed too?

**Comment by VSadov** [comment]
> Do we want to keep the notes about the suspension-async in the design doc, or should it be removed too?

I think we should keep the notes with details of both implementations and what worked/not - as a part of learning from the experiment. 

Perhaps could move the notes to a different place - like a learning doc.

**Pull request merged**
