### PR TITLE
[NativeAOT-LLVM] Enable shared generics

### PR DESCRIPTION
**Pull request by SingleAccretion**
A few changes:
1) Simplify `addCodeReloc` and enable all handles other than function ones.
2) Enable compiling and calling methods with a generic context.
3) Put the simple unboxing thunks on the same plan as the regular targets.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
We should wait for #2177 to get merged before merging this one, but it is ready for review.

**Review by yowl — APPROVED** [review]
This looks all good, thanks!

Are you/did you push the common changes upstream - the `WellKnownType.IntPtr` -> `Void).MakePointerType()` ones?

**Comment by SingleAccretion** [comment]
Will try to get these ones through together with the upcoming fix to VSD that will also touch common code.

**Comment by jkotas** [comment]
@SingleAccretion Could you please resolve the merge conflict?

**Comment by SingleAccretion** [comment]
@jkotas Done (CI included).

**Review by jkotas — APPROVED** [review]
Thank you!

**Pull request merged**
