### PR TITLE
Update Arcade

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fully update Arcade (including the eng/common folder) to the newest Arcade version.

The build in #2325 is broken because only the Arcade SDK was updated, not the eng/common folder.

This PR should fix the build for that PR once it is merged.

### CODE REVIEW

**Review by VivianaDuenas — APPROVED** [review]

**Review by carlossanlop — COMMENTED** [review]
I think we should also upgrade the Experiment.csproj and Experiment.Tests.csproj to net8.0.

Maybe that's why they showed up in this PR's file list in the "Unchanged files with check annotations" section?

**Comment by carlossanlop** [comment]
Shouldn't this target the standalone template branch?

Might as well update https://github.com/dotnet/runtimelab/blob/standalone-template/NuGet.config to include the dotnet8 transport.

**Comment by jkoritzinsky** [comment]
> Shouldn't this target the standalone template branch?
> 
> Might as well update [`standalone-template`/NuGet.config](https://github.com/dotnet/runtimelab/blob/standalone-template/NuGet.config?rgh-link-date=2023-06-30T22%3A24%3A41Z) to include the dotnet8 transport.

I was going to update that one differently by fixing the Arcade subscription + the feed change.

**Comment by jkoritzinsky** [comment]
> I think we should also upgrade the Experiment.csproj and Experiment.Tests.csproj to net8.0.
> 
> Maybe that's why they showed up in this PR's file list in the "Unchanged files with check annotations" section?

Nope the problem was that SourceLink changed feeds (it's in dotnet8 now).

**Comment by carlossanlop** [comment]
@VivianaDuenas once this PR is merged, you'll have to fetch the latest bits from feature/ManagedZLib, then rebase your local branch again.

**Review by carlossanlop — APPROVED** [review]

**Comment by jkoritzinsky** [comment]
@carlossanlop https://github.com/dotnet/runtimelab/pull/2330 will update the standalone template branch (it also needs approval as I added some custom changes there).

**Pull request merged**
