### PR TITLE
[NativeAOT-LLVM] Add the `WasmComponentTypeWit` item group

### PR DESCRIPTION
**Pull request by SingleAccretion**
Since pretty much all P2 projects will need to specify WITs, we can make it a bit more convenient with this item group.

Also, turns out we had `SharedLibrary` still disabled, so fix it a little and enable back.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
@dotnet/nativeaot-llvm

**Review by pavelsavara — APPROVED** [review]

**Comment by pavelsavara** [comment]
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=899534&view=logs&j=3ea61ca3-1b19-5893-30e5-3946b8108ef8&t=63b413f4-544e-53c1-ac31-863d0c88a1be)
[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/899534/logs/206)
```
nativeaot\SmokeTests\SharedLibrary\SharedLibrary\SharedLibrary.cmd [FAIL]
        The system cannot find the file specified.
        ---- DEBUG ASSERTION FAILED ----
        ---- Assert Short Message ----
        stopwatch.ElapsedMilliseconds < 10000
        ---- Assert Long Message ----
        
        
        
        Process terminated. Assertion Failed
        stopwatch.ElapsedMilliseconds < 10000
        
        
        wasm://wasm/.tmpPbxEqy-07fdbfca:1
        
        
        RuntimeError: unreachable
            at .tmpPbxEqy.abort (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[25246]:0x1219070)
            at .tmpPbxEqy.SystemNative_Abort (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[8430]:0x215ff2)
            at .tmpPbxEqy.S_P_CoreLib_Interop_Sys__Abort (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[24239]:0x111e48d)
            at .tmpPbxEqy.S_P_CoreLib_System_RuntimeExceptionHelpers__FailFast (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[21382]:0xdfa32f)
            at .tmpPbxEqy.S_P_CoreLib_System_Environment__FailFast_1 (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[10220]:0x23e47f)
            at .tmpPbxEqy.S_P_CoreLib_System_Diagnostics_DebugProvider__FailCore (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[15936]:0x870c3a)
            at .tmpPbxEqy.System_Diagnostics_TraceSource_System_Diagnostics_DefaultTraceListener__Fail_0 (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[22395]:0xf34cd3)
            at .tmpPbxEqy.System_Diagnostics_TraceSource_System_Diagnostics_DefaultTraceListener__Fail (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[21417]:0xe02a20)
            at .tmpPbxEqy.System_Diagnostics_TraceSource_System_Diagnostics_TraceInternal__Fail (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[18537]:0xb43cf5)
            at .tmpPbxEqy.System_Diagnostics_TraceSource_System_Diagnostics_TraceInternal__Assert_0 (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[13992]:0x64463f)
            at .tmpPbxEqy.System_Diagnostics_TraceSource_System_Diagnostics_Trace__Assert_0 (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[18520]:0xb3f37b)
            at .tmpPbxEqy.SharedLibrary_SharedLibrary_ClassLibrary__TestHttp (wasm://wasm/.tmpPbxEqy-07fdbfca:wasm-function[13975]:0x64300b)
            at Module.testHttp (file:///D:/a/_work/1/s/artifacts/tests/coreclr/wasi.wasm.Debug/nativeaot/SmokeTests/SharedLibrary/SharedLibrary/native/shared-library.mjs:7507:24)
            at file:///D:/a/_work/1/s/artifacts/tests/coreclr/wasi.wasm.Debug/nativeaot/SmokeTests/SharedLibrary/SharedLibrary/native/SharedLibrary.mjs:38:14
        
        Node.js v20.2.0
```

**Comment by yowl** [comment]
Should this PR have included the wit ?

**Comment by SingleAccretion** [comment]
> Should this PR have included the wit ?

The WIT was already there - the change just switched to using the new item group for it.

**Comment by yowl** [comment]
of course.

**Comment by pavelsavara** [comment]
I restarted the CI and it failed again with same messages [log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/899534/logs/276)

I will merge the #2899

**Pull request merged**
