### PR TITLE
NativeAOT-LLVM: Wasm separate DWARF debug to different file

### PR DESCRIPTION
**Pull request by yowl**
This PR utilises `gseparate-dwarf` to move the DWARF metadata to a separate file to reduce the main wasm size.

Debugging still works

image

### CODE REVIEW

**Comment by yowl** [comment]
With this we dont gain much:

HelloWasm debug, not split 28,545 KB, split 26,081 + 2,352 (dwp)
HelloWasm release not split 10,647 KB, split 8,826 + 1,578 (dwp)

Investigate https://github.com/llvm/llvm-project/issues/55538 and what is required to strip all DI.

**Comment by SingleAccretion** [comment]
@yowl I've just been randomly reading `emmc --help`, and came to realize that if we use the option in the PR's description (`emcc -gseparate-dwarf`, not `-gsplit-dwarf`), we will have the "PDB-like" experience we want, at least on browser.

**Comment by yowl** [comment]
oh lol, thanks I will try it !

**Comment by yowl** [comment]
rebased, but wasi-sdk does not have llvm-dwp so will need to look into that first

**Pull request closed without merging**
